Nri css
moroyou/yukimorohoshi pull request #3
Opened 2020-09-04 12:02 UTC by moroyou

NRIのCSS作成致しました。

2020-09-04 12:13 UTC, moroyou commented
すみません、、
見た目は9割くらいは再現できておりますがコードは大分強引かと思われるので一旦FBいただきたいです
下記に現状の不明点（不完全の部分）とそれに対する自分の仮説も書いておきます。



**★現時点できていない箇所（ページの上から）**

1　グローバルの幅（左端）が調整できない
2　ダウンロードボタンの“＞”が真ん中にいかない
3　ビジネスモデルの特徴　人が支える未来が設定できない
4　NRIの強みの表が全体サイズ感が違う。
5　企業情報行こうのリストの“＞”が左詰めできない

＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝

**★上記に対する仮説（実行してはいるがうまくいかない）**

1　width広げたりして見たのですが理解できてないです。
2　padding などで微調整するしかない？
3　div 活用してtext-algin: right left?を各々作成？
4　本来はul で作成した方がいいのだろうか。2列目の幅調整のバランンスが取れない
5　ここはアイデアが思いつかないです。。

2020-09-05 00:53 UTC, ykyk1218 commented on CSS/nri.css
> +    position: ;
値が抜けてしまっています 🙃

2020-09-05 00:56 UTC, ykyk1218 commented on CSS/nri.css
> +.mainvisualtext {
クラス名で単語が複数になる場合は
キャメルケース、ケバブケース、スネークケースのいずれかにするようにしてください

2020-09-05 02:17 UTC, ykyk1218 commented on CSS/nri.css
> +}/*(元々青色で囲っていたところ)*/
globalNavi に margin-left と margin-bottom が 入ってしまっていますが、必要ないかなと思います 😄

2020-09-05 02:17 UTC, ykyk1218 commented on CSS/nri.css
> +    max-width: 1100px;
メインのコンテンツの幅を 1100px にしてますが、そんなに必要ないかなと思います
ここはコンテンツの幅に合わせた方が良さそうです。

![image](https://user-images.githubusercontent.com/830861/92295817-17e96e00-ef69-11ea-88b0-89e27a2c85a0.png)

2020-09-05 02:18 UTC, ykyk1218 commented
子要素が親要素の幅を超えてしまっているのはよくないので、ちゃんと収まるように修正をお願いします！
![image](https://user-images.githubusercontent.com/830861/92295841-6434ae00-ef69-11ea-951f-6f8d18d885db.png)

2020-09-05 02:59 UTC, ykyk1218 commented on CSS/nri.css
> +    float: left;
ナビゲーションは float 使うよりも他の方法で横並びさせるようがいいですね。
float の役割はそもそも横並びさせるもの、というよりかは要素を回り込ませるものだったりするので、今回の場合には当てはまらないかと思います。

参考
https://haniwaman.com/side-by-side/

2020-09-06 07:26 UTC, moroyou commented on CSS/nri.css
> +    max-width: 1100px;
一旦サイズを縮めるという形で編集してみましたが
そもそもdisplay:inline-blockなどで行うべきとのことでしたらすみません！
（仮にその場合は、他の要素を微修正を結構する事になる認識です！）

2020-09-06 07:27 UTC, moroyou commented on CSS/nri.css
> +    float: left;
ありがとうございます！
ナビは最初に編集していたこともあり、この辺り少し理解不足でしたが参考URLで理解進みました！

2020-09-08 12:18 UTC, ykyk1218 commented on CSS/nri.css
> +    max-width: 1100px;
余計な幅があるがゆえに...
![image](https://user-images.githubusercontent.com/830861/92475527-80aa4200-f218-11ea-9e38-37c65a31fa86.png)


この中の pタグでに `padding-left` などを使って調整しないといけないのですが
![image](https://user-images.githubusercontent.com/830861/92475547-8869e680-f218-11ea-9198-690cdc82a34b.png)

そもそも `<section id="maincontent">` の幅を適切にしておけば、その中の pタグ `padding-left` で調整する必要がないのでは？と思ったのでこの指摘をしました。

2020-09-08 12:25 UTC, ykyk1218 commented
<img width="1031" alt="NRIの強み：ビジネスモデルの特徴" src="https://user-images.githubusercontent.com/830861/92476350-c6b3d580-f219-11ea-95d3-e9b1b72b2b0f.png">

2020-09-08 12:28 UTC, ykyk1218 commented
どっちのリンクの端に寄せるようにして、全体の幅を縮めるようにしてみてください
リンクにつける CSS は基本一緒にしておくとなお良しです。
![image](https://user-images.githubusercontent.com/830861/92476475-fa8efb00-f219-11ea-8715-20fe796484cf.png)

2020-09-08 12:31 UTC, ykyk1218 commented
全体的に隙間がお手本サイトと揃っていないですね... 😖
もう少し近づけるようにしてみてください

<img width="931" alt="NRIの強み：ビジネスモデルの特徴" src="https://user-images.githubusercontent.com/830861/92476832-86a12280-f21a-11ea-8c8a-c9dae2b3f63b.png">

2020-09-08 12:34 UTC, ykyk1218 commented
お手本のサイトを参考にラインを揃えることを意識してみてください

<img width="1035" alt="NRIの強み：ビジネスモデルの特徴" src="https://user-images.githubusercontent.com/830861/92477131-05965b00-f21b-11ea-82f8-7eea28b15145.png">

2020-09-08 12:40 UTC, ykyk1218 commented
これはちょっとしたヒントですが、画像の赤ワクで囲んだような div を1つ作って上げると中のコンテンツを揃えやすくなるかと思います。


<img width="530" alt="スクリーンショット_2020-09-08_21_37_00" src="https://user-images.githubusercontent.com/830861/92477530-b997e600-f21b-11ea-9349-da9c00ba2c6f.png">

2020-09-09 13:57 UTC, moroyou commented
ありがとうございます！
特に最後のヒント部分でスッキリしている気がします。（そもそもそこに自分で気づけという話ですが、、）
ご指摘部分以外にも本物に寄せるために細かいところも修正してみました。
ご確認お願いします🙇‍♂️

2020-09-10 20:55 UTC, n06Ar requested changes
レビューしました。
一部タグで開始タグがないのに終了タグがあるケースがあり、インデントが崩れていました。
ご確認をお願いいたします。

また、この課題はリポジトリに`html-nri`ディレクトリを作成しその中で実装する認識です。
一度カリキュラムのご確認をお願いいたします。

2020-09-10 20:55 UTC, n06Ar commented on CSS/nri.css
> +#pagebodyMain .heading-typeA {
`A`や`B`、`1`や`2`などのマジカルナンバー的な命名は避けてください
他の人や後で見返した時に、何を指しているか予測が難しいためです。

2020-09-10 20:55 UTC, n06Ar commented on CSS/nri.css
> +div #glaph {
このセレクタは、343行目の`#glaph`と同一の意味になります。
祖先にdivを持ったID属性が`glaph`に対してスタイルを当てるというセレクタですが、ID属性はそもそも1Webページにつき一つしか使えません。

2020-09-10 20:55 UTC, n06Ar commented on CSS/nri.css
> +    display: inline-block!important;
!importは最終手段としての理由以外では決して使用しないでください。
!importを使用すると他の要素でも使われ最終的に詳細度の戦いになります。

2020-09-10 20:55 UTC, n06Ar commented on CSS/nri.css
> +    margin: right;
marginの値にrightはないので本来やりたかったことを確認してください

2020-09-10 20:55 UTC, n06Ar commented on nri.html
> +    <link rel="stylesheet" href="CSS/nri.css">
リセットCSSを入れてください
クロスブラウザを考慮すると一度CSS のベースを統一する必要があります

2020-09-10 20:55 UTC, n06Ar commented on nri.html
> +                            <li class="lo-navcontent"><a href="https:">社長メッセージ</a></li>
hrefは全て`#`にしてください。

2020-09-10 20:55 UTC, n06Ar commented on nri.html
> +            <li class="first-followus"><img src="image/facebook.logo.jpg" alt="facebokkのロゴ" width="30px" height="30px">
細かいことで申し訳ないのですが、alt属性でタイポしています

2020-09-10 20:55 UTC, n06Ar commented on nri.html
> +                        <li><img src="image/linkedin.logo.png" alt="linkedinのロゴ" width="30px" height="30px"></li>
width属性やhight属性でピクセル指定する場合は、整数のみでよくpxは不要です。

2020-09-10 20:55 UTC, n06Ar commented on nri.html
> +                    <li><img src="image/glassmark.svg" alt="検索" 　width="25px" height="25px"></li>
widthの前に全角スペースが入っています
これだと`　width`と認識され横幅が反映されません

2020-09-10 20:55 UTC, n06Ar commented on nri.html
> +                    <li><img src="image/earth.svg" alt="地球マーク" 　width="25px" height="25px"></li>
こちらも`　width`になっています

2020-09-10 20:55 UTC, n06Ar commented on nri.html
> +                        <h1 class="heading-typeA"><img src="image/nri-contentlogo.png" alt="nrimロゴ" width="20px"
alt属性にロゴと書かれていますが、こちらはロゴマークではないように見受けられます。
またこちらは、装飾的な意味合いの方が強い様に見えるので、CSSで記述するか`aria-hidden`属性をつけてスクリーンリーダーに読まれない様にしてください。

2020-09-10 20:55 UTC, n06Ar commented on nri.html
> +                    <div id="snslogo">
id属性は、1htmlファイルに対して同一の名前をつけることはできません
こちらの[id](https://developer.mozilla.org/ja/docs/Web/HTML/Global_attributes/id)を参照してください

2020-09-10 20:55 UTC, n06Ar commented on nri.html
> +    <div id="copyright">
著作表記はfooterタグの中に記述する様にしてください。
footerタグには、著作関係情報も含みます。

2020-09-10 20:55 UTC, n06Ar commented on nri.html
> +            <p class="toicpatch">NRIトップ &gt; 企業情報 &gt; NRIの強み：NRIのデジタルビジネス戦略</p>
ここのパンくずメニューは`NRIの強み：NRIのデジタルビジネス戦略`を除いてリンクにしてください

2020-09-10 20:55 UTC, n06Ar commented on CSS/nri.css
> +    border-bottom-color: #999;
この色は、border-bottomで同時に定義することができます
書き方は、[こちら](https://developer.mozilla.org/ja/docs/Web/CSS/border)を参考にしてください

2020-09-10 20:55 UTC, n06Ar commented on CSS/nri.css
> +    content: "Follow US";
こちらのcontentで`Follow US`をCSSに書いている意図はなんでしょうか？
現状では、スクリーンリーダーが読み上げなくなり、ここの項目がSNSのフォローを促していることがわかりません

2020-09-10 20:55 UTC, n06Ar commented on CSS/nri.css
> +    border-bottom-style: dotted;
442行目でsolidをdottedに置き換えても記述できます

2020-09-10 20:55 UTC, n06Ar commented on CSS/nri.css
> +    width: -webkit-fill-available;
`-webkit-fill-available`はベンダープレフィックスのついた値設定されていますが、他のブラウザの考慮がされていません。
この設定はWebkitを使っているブラウザ（ChromeとSafari）のみでFirefoxには適用されないです。

2020-09-10 20:55 UTC, n06Ar commented on CSS/nri.css
> +    background: url(../image/PDF_img.png)
画像が元のページのPDF画像と異なりますが、意図はありますでしょうか？

2020-09-10 20:55 UTC, n06Ar commented on CSS/nri.css
> +    content:"   ";
contentにスペースを指定する場合は、`\00a0`を指定する必要があります。
またスペースで余白を作るならmarginを使用してください。

2020-09-10 20:55 UTC, n06Ar commented on CSS/nri.css
> +    max-width: 100%;
`width`ではなく`max-width`で100%を指定した意図は何でしょうか？
100%は相対的な値のため確認したい次第です。

2020-09-10 20:55 UTC, n06Ar commented on CSS/nri.css
> +    max-width: 1800px;
`max-width`を`1800px`指定した意図は何でしょうか？
4K以上の解像度のモニターでみているケースでのみ長さを固定する意図を確認したい次第です。

2020-09-10 20:55 UTC, n06Ar commented on CSS/nri.css
> +    color: rgb(107, 105, 105);
他で使われているカラーコードではなく、rgbを使っている意図は何でしょうか？
アルファ値を設定するためにrgbaを使うのはよくあることですが、rgbを唯一使われていたので確認したい次第です。

2020-09-10 20:55 UTC, n06Ar commented on nri.html
> +    </div>
ここのdivの終了タグは、終了すべき開始のdivタグがないです

2020-09-12 00:59 UTC, moroyou commented on CSS/nri.css
> +    content: "Follow US";
結論は調整がしやすかっただけになります。
li でSNSロゴ並べた際、上記よりも前に登場している(share)同様の調整の仕方でできるなと思いCSSで読みとっておりました。
`現状では、スクリーンリーダーが読み上げなくなり、ここの項目がSNSのフォローを促していることがわかりません
`
ここの観点が抜けていたので、htmlの方が良いのであれば修正致します！

2020-09-12 00:59 UTC, moroyou commented on CSS/nri.css
> +    width: -webkit-fill-available;
確認した際そもそも、ここの指定自体が必要なさそうなのではということに気づきました。。。
何かの調整をしたかった際にdevツールを弄りながら調整した際にfitしたものをそのまま使用してしまっていました。

2020-09-12 01:00 UTC, moroyou commented on CSS/nri.css
> +    max-width: 100%;
すみません、自分でも混乱してしまい、意図がどこであったか思い出せませんが
おそらく、ページ全体に広げるために指定した意図でした。
画面最上部のナビは横幅いっぱいになるものの故に`max-width`を使い画面一杯にしたいのイメージだったはずです。

`max-width`→最大幅の指定
`width`→幅の指定
ですが、調べてもここがイマイチ理解できてないと思うので質問します。

2020-09-12 01:00 UTC, moroyou commented on CSS/nri.css
> +    max-width: 1800px;
こちらも上記と似ておりますが
全体の幅を先に指定した方が揃えやすいので指定したはずで
1800については何か調べた際に指定しているケースがあって設定してしまった記憶です。

ここも後ほど質問致します。

2020-09-12 01:00 UTC, moroyou commented on CSS/nri.css
> +    color: rgb(107, 105, 105);
意図は特になく、色の調整の仕方どのようにできるのかを確認していた名残でそのままにしてしまいました。
アルファ値(透過)の意味も本件で知ったので、ここも基本的には不要であれば修正致します！

2020-09-12 01:02 UTC, moroyou commented
```
また、この課題はリポジトリにhtml-nriディレクトリを作成しその中で実装する認識です。
一度カリキュラムのご確認をお願いいたします。
```

すみません、こちらは完全に理解が欠けていたので気をつけます。

2020-09-14 10:20 UTC, moroyou commented
上記記載のコメント以外に
先日のスクールの際、のぶさんから口頭でご指摘いただいた部分も含めて変更しました。（下記参照）


**①画面最上部のビル写真(id=topimg)は`object-fit` はNGとのことだったので、そもそも画像サイズを編集して合わせました。
②カラー名の統一
③`aria-hidden`の追加
また、ディレクトリ名はGitから編集してみました。**


総じて、単元習得までに時間はかかっていますが、普段の勉強時間が少なく定着仕切ってない部分もあるので
imoでもいいので厳しめコメントしていただけると助かります。（後々に直結すると思うので）
ご確認よろしくお願い致します。
※一応今月最終週にPHP入るのが短期目標です。

2020-09-14 23:36 UTC, n06Ar commented
> ①画面最上部のビル写真(id=topimg)はobject-fit はNGとのことだったので、そもそも画像サイズを編集して合わせました。
これは認識が違います。私の言い回しがわかりづらく申し訳ありません。

`object-fit`がNGではなく、`object-fit:none;`を使うと解決できないのでNGといった意図です。
逆に`object-fit`を使い、値を`none`以外にすると良いと言う意味です。

> また、ディレクトリ名はGitから編集してみました。
こちらはどういった変更でしょうか？可能であればどこでその変更をしたかお教えいただけますでしょうか？

2020-09-15 23:22 UTC, n06Ar requested changes
レビューしました。
ご確認をお願いいたします。

また、共有のコメントとして、idとclassの命名がキャメルケースやスネークケースと統一されていない様子が見受けられました。命名方法の統一をお願いします。

2020-09-15 23:22 UTC, n06Ar commented on nri.html
> +                    <img class="topimg" src="image/top.page renew.jpg" 　"aria-hidden=" true" width="100%" height="100%">
`"aria-hidden=" true"`となっていますが、正しくは`aria-hidden="true"`です

2020-09-15 23:22 UTC, n06Ar commented on nri.html
> +            <a href="#">NRIトップ</a> &gt; <a href="#">企業情報</a>&gt; <p class="toicpatch"></p>NRIの強み：NRIのデジタルビジネス戦略</p>
`&gt;`は文書上の意味を持たない装飾なので、装飾の役割であるCSSを使うと良いです

2020-09-15 23:22 UTC, n06Ar commented on nri.html
> +    <meta property="og:type" content="website" />
他にもOGPタグはあるので追加してください

2020-09-15 23:22 UTC, n06Ar commented on nri.html
> +            <a href="#">NRIトップ</a> &gt; <a href="#">企業情報</a>&gt; <p class="toicpatch"></p>NRIの強み：NRIのデジタルビジネス戦略</p>
パンくずリストはナビゲーションなので`nav`タグで囲います
さらにいうとパンくず**リスt**なので、`ul`と`li`タグを使用します

2020-09-15 23:22 UTC, n06Ar commented on nri.html
> +                <div class="logo"><img src="image/nrilogo.png" alt="NRIロゴ" width="90px" height="90px"></div>
このロゴもリンクだったはずなので確認してみてください

2020-09-15 23:22 UTC, n06Ar commented on nri.html
> +                    <li><img src="image/earth.svg" alt="地球マーク" width="25px" height="25px"></li>
ここは言語切り替えの機能なので、地球マークでその機能について伝わるか考えてみてください

2020-09-15 23:22 UTC, n06Ar commented on nri.html
> +    <link rel="stylesheet" href="CSS/nri.css">
同じディレクトリにあるはずのCSSファイルが参照方法が異なる意図はなんでしょうか？

2020-09-15 23:22 UTC, n06Ar commented on nri.html
> +                    <li><img src="image/glassmark.svg" alt="検索" width="25px" height="25px"></li>
widthとheightは、ピクセルで指定する場合では`px`の単位は不要です。

2020-09-15 23:22 UTC, n06Ar commented on CSS/nri.css
> +body {
Safariで確認した時に明朝体のフォントが表示されています確認をお願いします

2020-09-15 23:22 UTC, n06Ar commented on nri.html
> +    <div id="page">
このdivがある意図は何でしょうか？
CSSでも使用されていませんが設定されている意図を確認したい次第です。

2020-09-15 23:22 UTC, n06Ar commented on CSS/nri.css
> +.btn {
ダウンロードボタンのクラスがボタンクラスに関連したスタイルを定義している312行目以外にある意図は何でしょうか？
関連機能を離れた場所にコードを書くとコードの可読性が落ちます。

2020-09-15 23:22 UTC, n06Ar commented on CSS/nri.css
> +    border: solid 1px #005bac;
背景色がと同じ色であれば枠線を定義する必要がないと見受けられますが、意図はありますでしょうか？

2020-09-15 23:22 UTC, n06Ar commented on CSS/nri.css
> +    text-align: center;
ここのtext-alignは機能していないです。
小要素のpタグは、display:blockが割り当てられるためtext-alignは効きません。
display block や inline で調べてみてください。

2020-09-15 23:22 UTC, n06Ar commented on CSS/nri.css
> +    content:"\00a0";
余白目的のスペース入力であれば、marginまたはpaddigで余白を作るようにしてください

2020-09-15 23:22 UTC, n06Ar commented on CSS/nri.css
> +    padding-left: 40px;
クラス名からすると`text-align:left`があることが想像できますが、`padding-left`まであることは想像できません。
CSSの属性名をクラス名にする汎用的なクラス名の命名で、クラス名と異なる属性が設定することはやめてください。
このクラスを利用した他者に対して混乱を招きます。

2020-09-15 23:22 UTC, n06Ar commented on CSS/nri.css
> +.totalgraph {
このスタイルが、351行目と分離されている意図は何でしょうか？
不要な分離は混乱を招きます。

2020-09-15 23:22 UTC, n06Ar commented on CSS/nri.css
> +.totalgraph {
こちらのgraphが命名されていますが、表であればtableの方が良いです。
図を用いたものを想起させますが、このコンテンツに図は使われていないので別の命名をした方が良いです。

2020-09-15 23:22 UTC, n06Ar commented on CSS/nri.css
> +    content: ">  ";
類似の箇所があるので、他の場所も確認してください。
スペース文字での余白は行わず、marginかpaddingを使用してください。
スペース文字は装飾的な余白を作る目的ではないためです。

2020-09-15 23:22 UTC, n06Ar commented on CSS/nri.css
> +    border-bottom: solid 1px;
solidをdottedで上書きしていますが、最終的にdottedで表示する理解で良いでしょうか？
それであれば下記のように1行で書くことができます。
```css
border-bottom: 1px dotted #999;
```
また、メディアクエリを使用した指定以外での同一のセレクタでスタイルで、スタイルの上書きはしないようにしてください。
見返した時に不具合なのか正しい実装なのか混乱します。

2020-09-15 23:22 UTC, n06Ar commented on CSS/nri.css
> +h3 {
基本的にですが、要素型セレクタの単体での使用は避けるようにしてください。
リセットCSS系や全ウェブページで共通して使う下地的なCSSであれば良いのですが、今回であればh3の指定先にはある程度の役割があることと要素型セレクタから何に対してスタイルを当てているかわからないので、クラス名で指定するようにしてください。

2020-09-15 23:22 UTC, n06Ar commented on CSS/nri.css
> +h3.subinfo-title {
576行目では、要素型セレクタを組み合わせず`.subinfo-title`単体で使われていますが、この行で`subinfo-title`を指定している意図は何でしょうか？
また、このセレクタは使用されていないのですが、実際には使われなかった理解でよろしいでしょうか？

2020-09-15 23:22 UTC, n06Ar commented on nri.html
> +                        <p class="btn">デジタルが開く近未来（NRIのDX)<br>(4.06MB)</p>
`p`を`a`で囲うようにするか、`p`を`button`に置き換えるなどしてください。
実際の挙動と異なるためです。

2020-09-15 23:22 UTC, n06Ar commented on nri.html
> +                        <p class="btn">デジタルが開く近未来（NRIのDX)<br>(4.06MB)</p>
`>`の位置が元のページと比較して明らかに右寄りなため、調整をお願いいたします。

2020-09-15 23:22 UTC, n06Ar commented on CSS/nri.css
> +.totalgraph .nripower {
`.totalgraph`をつけることで詳細度を細かくする意図は何かありますでしょうか？
`.nripower `は、固有のクラス名かつ一箇所でしか使われていないため確認したい次第です。

2020-09-15 23:22 UTC, n06Ar commented on nri.html
> +                            <p class="nripower">NRIの強み</p>
`nripower`の命名は、idとして使いたい程度に固有な場所を示すな命名です。
理由としては、仮に同一のデザインを別のページに適用する際に固有の名称をクラス名とすると扱いづらくなります。`totalgraph`のクラスの見出しクラスまたは、タイトルのクラスである命名にすると他のページで似たデザインがあった時に使いやすくなります。

2020-09-15 23:22 UTC, n06Ar commented on nri.html
> +                    <div class="totalgraph">
左右の余白が異なるので調整してください
![NRIの強みの余白](https://user-images.githubusercontent.com/56122838/93273535-0880e500-f7f3-11ea-873f-9053b4944450.png)

2020-09-15 23:22 UTC, n06Ar commented on nri.html
> +                        <div id="glaph">
`>`の位置が元のページと異なります。ご確認をお願いします。

2020-09-15 23:22 UTC, n06Ar commented on nri.html
> +                <div id="snslogo-first">
`Share`をCSSのcontentで表示している意図は何でしょうか？
Shareがなければ、この後のSNSアイコンの意味が伝わりづらくなります。

2020-09-15 23:22 UTC, n06Ar commented on nri.html
> +                        <p class="mainarticle">NRI では、企業の DX に向けた取り組みについて、既存ビジネスの業務プロセス変革に寄与する DX を<br>
基本的に、pタグの中で必要でない限りbrタグは使用しないでください。
今回は課題の対象外ですが、レスポンシブデザインを考慮すると不自然な箇所で改行することになります。
デザインと同一にする目的であれば、フォントサイズや余白を見直して見てください

2020-09-15 23:22 UTC, n06Ar commented on nri.html
> +                    <img class="topimg" src="image/top.page renew.jpg" 　"aria-hidden=" true" width="100%" height="100%">
ここの画像は、横幅を調整した時に画像が潰れるのはNGです
object-fitのcoverなどを使って調節してください

2020-09-15 23:51 UTC, n06Ar commented on nri.html
> +                                <p><a href="#">NRIの歩みと持続的な成長</a></p>
ここのリンクをHoverしたときの表示が実装されていないのでご確認をお願いします。

2020-09-18 10:15 UTC, moroyou commented on nri.html
> +    <meta property="og:type" content="website" />
実施致しましたが、これの限度（どのくらいの粒度でどのくらいの種類記載すべきか）がイマイチ検索しても不明でした。追加補足有ればご教示頂けますと幸いです。

2020-09-18 10:24 UTC, moroyou commented on nri.html
> +    <div id="page">
仰る通りで不要かと思いますが、こちらを消すとTOPの画像がずれるのは何故かがどうしても不明です。
ここをカバーするためのobject-fit 等なのかと想定しておりますが、ここの理解がイマイチできておりません。。。

2020-09-18 10:24 UTC, moroyou commented on CSS/nri.css
> +    border: solid 1px #005bac;
ここは枠線削除しました。

2020-09-18 10:37 UTC, moroyou commented on CSS/nri.css
> +    text-align: center;
こちらは外すと左に全体が寄ってしまうことから、効いてはいるのでは無いか？と感じたのですが
何故かが理解できておりません。
pタグに関しては　class=btn と設定し、CSSでinline-block の割り当てをしているので効く認識でしたが間違えていたらすみません、、、。

2020-09-18 10:40 UTC, moroyou commented on nri.html
> +                            <p class="nripower">NRIの強み</p>
`idとして使いたい程度に固有な場所を示すな命名です。`
本当にすみません、、、、読解力なさすぎてここから理解できなくなりました。

今回の命名に関しては
同一デザインを作成する場合に固有名詞すぎる命名だと後から色々面倒ということで、もう少し汎用的な命名にすべきということでしょうか？

2020-09-18 10:40 UTC, moroyou commented on nri.html
> +                        <p class="mainarticle">NRI では、企業の DX に向けた取り組みについて、既存ビジネスの業務プロセス変革に寄与する DX を<br>
こちら削除しました。

2020-09-18 10:48 UTC, moroyou commented
不明点や気になるところは個別でコメント致しました。
またGitの部分について修正したつもりなのですが、理解違うようでしたらすみません。

![image](https://user-images.githubusercontent.com/67782125/93589226-7b52b180-f9e7-11ea-9e53-d0beb37fdd9c.png)`
⬆️html-nriディレクトリ（フォルダ）をリポジトリの直下におき`


![image](https://user-images.githubusercontent.com/67782125/93589350-a89f5f80-f9e7-11ea-9d2f-a87702f5e419.png)

⬆️その中にNRI関連のコードや画像を入れる

添付画像でできている認識だったのですが（余分なnkou があるのはすみません）この認識も全く違いますでしょうか。
毎回FB多くて大変申し訳ございませんが、ご確認宜しくお願い致します🙇‍♀️

2020-09-18 11:56 UTC, n06Ar commented on nri.html
> +                            <p class="nripower">NRIの強み</p>
> 同一デザインを作成する場合に固有名詞すぎる命名だと後から色々面倒ということで、もう少し汎用的な命名にすべきということでしょうか？

汎用的な命名にすべきという意図です。
（ただしバリエーションの違いを出すために、汎用的なクラス名を組み合わせて固有に近いクラス名を使用することはあります）

面倒というのもありますが、一番は使い回しができなくなるからです。

例えば、下記のような _今日の天気_ を表示するところがあったとします。
下記のように今日の天気の見出しのクラスのために、`today-weather`命名します。
```html
<section class="weather-content">
    <h1 class="today-weather">今日の天気</h1>
    <ul>
        <li>....</li>
    </ul>
</section>
```

この後に今日の天気のようなデザインで、 _明日の天気_ を表示することになったとします。
同じデザインにしたいので、今日の天気のクラスを使って使い回します。

```html
<section class="weather-content">
    <h1 class="today-weather">明日の天気</h1>
    <ul>
        <li>....</li>
    </ul>
</section>
```
クラス名が、`today-weather`で今日の天気を示す命名をしていますが、実際表示するのは明日の天気ですよね？
この時点でクラス名と表示するものがおかしい状態になります。
他の人が読んだ時に **確実に混乱します** 。

ではこういった場合にどう命名をするかというと、下記のように命名します。

`weather-content__title`クラスという見出し用の共通のクラスを使用します。
もしバリエーション違いを作る必要があればクラスを追加し組み合わせて対応します。
（今回はこの方法は紹介しないので、調べてみてください）

```html
<section class="weather-content">
    <h1 class="weather-content__title">今日の天気</h1>
    <ul>
        <li>....</li>
    </ul>
</section>

<section class="weather-content">
    <h1 class="weather-content__title">明日の天気</h1>
    <ul>
        <li>....</li>
    </ul>
</section>
```

2020-09-18 22:20 UTC, n06Ar commented on CSS/nri.css
> +    text-align: center;
現在、左に寄るのは、aタグを追加したからです。 
aタグを削除すると動作しないことがわかります。
この[text-align](https://developer.mozilla.org/ja/docs/Web/CSS/text-align)の記事を読んでください

2020-09-18 22:22 UTC, n06Ar commented on nri.html
> +    <meta property="og:type" content="website" />
OGPが表示できるレベルは入れてください。
[このページ](https://ferret-plus.com/13065)の1ページの内容は最低限入れてください。

2020-09-18 22:39 UTC, n06Ar commented on nri.html
> +                    <img class="topimg" src="image/top.page renew.jpg" 　"aria-hidden=" true" width="100%" height="100%">
類似箇所が直っていないので確認してください

2020-09-18 23:17 UTC, n06Ar requested changes
追加でレビューしました。

一部横展開（類似箇所の確認）が漏れている印象です。確認をお願いします。

また、個人的な感想ですが、複数の要因による問題が多いように思います。
問題を分析する時は細かく分けて分析をするようにしてください。
一つの要素に焦点をあて値を変えて問題がなければ他の要素を変えてみるなどしてみてください。

2020-09-18 23:17 UTC, n06Ar commented on CSS/nri.css
> +/* ダウンロードボタン*/
不要なコメントは削除するようにしてください

2020-09-18 23:17 UTC, n06Ar commented on nri.html
> +    <div id="page">
> 仰る通りで不要かと思いますが、こちらを消すとTOPの画像がずれるのは何故かがどうしても不明です。

nri.css の 154行目のセレクタの条件に合わないためです。

下記は154行目のセレクタですが、[子孫結合子](https://developer.mozilla.org/ja/docs/Web/CSS/Descendant_combinator)を使っているので、条件が限定的になっています。

```
#page .topimg
```

試して欲しいのですが、nri.css の 154行目の`#page`と` <div id="page">`の閉じタグを含めて削除してみてください
影響はないはずです。

基本的にですが、問題が発生した場合はその問題が発生した箇所で解決できないかを考えてください。
今回のように問題があったところより、親のスコープにしてしまうと、他の要素に影響を与えてしまい複数の問題が発生します。

2020-09-18 23:17 UTC, n06Ar commented on nri.html
> +                                <p><a href="#">NRIの歩みと持続的な成長</a></p>
`>`の位置が元のページと異なるので、再度確認をお願いします。
![Screen Shot 2020-09-19 at 7 38 04](https://user-images.githubusercontent.com/56122838/93652103-cd7aed80-fa4e-11ea-940c-526f93a8cce6.png)

2020-09-18 23:17 UTC, n06Ar commented on nri.html
> +                        <li><a href="#">ナレッジ・インサイト</a></li>
このナレッジ・インサイトは、このリストと同一のレベルの内容でしょうか？
この辺りを元のサイトで扱いを確認してください（他の箇所も同様です）

2020-09-18 23:17 UTC, n06Ar commented on nri.html
> +            <div id="subinfo">
ブラウザの横幅が1300px以上の時に、元のサイトでは、全体が中央寄せになるところが中央寄せになっていません。

2020-09-18 23:17 UTC, n06Ar commented on nri.html
> +        <header id="pagehead">
全体的にHeaderの内容の位置に違和感があるので元のサイトと見比べて確認をしてください

2020-09-18 23:28 UTC, n06Ar commented
> 不明点や気になるところは個別でコメント致しました。
> またGitの部分について修正したつもりなのですが、理解違うようでしたらすみません。
> 
> ![image](https://user-images.githubusercontent.com/67782125/93589226-7b52b180-f9e7-11ea-9e53-d0beb37fdd9c.png)` ⬆️html-nriディレクトリ（フォルダ）をリポジトリの直下におき`
> 
> ![image](https://user-images.githubusercontent.com/67782125/93589350-a89f5f80-f9e7-11ea-9d2f-a87702f5e419.png)
> 
> ⬆️その中にNRI関連のコードや画像を入れる
> 
> 添付画像でできている認識だったのですが（余分なnkou があるのはすみません）この認識も全く違いますでしょうか。
> 毎回FB多くて大変申し訳ございませんが、ご確認宜しくお願い致します🙇‍♀️

一度ですが、`リポジトリ`を`ディレクトリ`、`フォルダ`の違いを説明できるようにしてください。

一番上の画像でやっていることは、リポジトリの名前を変更しています。
リポジトリの名前は元のもので実施することと書かれているので元に戻してください。

二つの画像だとブランチのリストが写っているだけで、NRIのコードや画像が入っているということがわかりません。

私の説明が悪く申し訳ないです。
やっていただきたいことは、このリポジトリ（html-nri）の`nri-css`ブランチのフォルダ構成を下記にして欲しいという意図です

```
リポジトリのディレクトリ
├── html-nri
│   ├── CSS
│    │  ├── normalize.css
│    │  └── nri.css
│   ├── image
│    │  ├── earth.svg
│    │  ├── facebook.logo.jpg
│    │  ├── glassmark.svg
│    │  ├── linkedin.logo.png
│    │  ├── nri-contentlogo.png
│    │  ├── nrigraph_img_01.jpg
│    │  ├── nrilogo.png
│    │  ├── pdf-icon.svg
│    │  ├── PDF_img.png
│    │  ├── top.page.jpg
│    │  ├── top.page renew.jpg
│    │  └── Twitter_Social_Icon_Square_Color.png
│  └── nri.html
└── README.md
```

このリポジトリ内で次の課題をするのですが、現状だと現在の課題と次の課題が混ざってしまいますよね？
それをディレクトリを分けて避けたい意図です。

2020-09-21 07:58 UTC, moroyou commented
> > 不明点や気になるところは個別でコメント致しました。
> > またGitの部分について修正したつもりなのですが、理解違うようでしたらすみません。
> > ![image](https://user-images.githubusercontent.com/67782125/93589226-7b52b180-f9e7-11ea-9e53-d0beb37fdd9c.png)` ⬆️html-nriディレクトリ（フォルダ）をリポジトリの直下におき`
> > ![image](https://user-images.githubusercontent.com/67782125/93589350-a89f5f80-f9e7-11ea-9d2f-a87702f5e419.png)
> > ⬆️その中にNRI関連のコードや画像を入れる
> > 添付画像でできている認識だったのですが（余分なnkou があるのはすみません）この認識も全く違いますでしょうか。
> > 毎回FB多くて大変申し訳ございませんが、ご確認宜しくお願い致します🙇‍♀️
> 
> 一度ですが、`リポジトリ`を`ディレクトリ`、`フォルダ`の違いを説明できるようにしてください。
> 
> 一番上の画像でやっていることは、リポジトリの名前を変更しています。
> リポジトリの名前は元のもので実施することと書かれているので元に戻してください。
> 
> 二つの画像だとブランチのリストが写っているだけで、NRIのコードや画像が入っているということがわかりません。
> 
> 私の説明が悪く申し訳ないです。
> やっていただきたいことは、このリポジトリ（html-nri）の`nri-css`ブランチのフォルダ構成を下記にして欲しいという意図です
> 
> ```
> リポジトリのディレクトリ
> ├── html-nri
> │    ├── CSS
> │    │  ├── normalize.css
> │    │  └── nri.css
> │    ├── image
> │    │  ├── earth.svg
> │    │  ├── facebook.logo.jpg
> │    │  ├── glassmark.svg
> │    │  ├── linkedin.logo.png
> │    │  ├── nri-contentlogo.png
> │    │  ├── nrigraph_img_01.jpg
> │    │  ├── nrilogo.png
> │    │  ├── pdf-icon.svg
> │    │  ├── PDF_img.png
> │    │  ├── top.page.jpg
> │    │  ├── top.page renew.jpg
> │    │  └── Twitter_Social_Icon_Square_Color.png
> │    └── nri.html
> └── README.md
> ```
> 
> このリポジトリ内で次の課題をするのですが、現状だと現在の課題と次の課題が混ざってしまいますよね？
> それをディレクトリを分けて避けたい意図です。

＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝

すみません。。。ありがとうございます。
一旦勉強し直したので自分なりにまとめます。（ほぼのぶさんの図の通りかと思いますが）
今回は説明例としてGitをアマゾンか何かの**【倉庫】**に例えます。


**【そもそもの言葉の違い】**
・リポジトリ＝倉庫自体のこと
・ディレクトリ/フォルダは同じ意味＝倉庫にあるダンボールや荷物📦
┗※ただ厳密には異なり、ディレクトリの中にフォルダがあるイメージ（容れ物）

**【今回の話と質問】**
リポジトリ名は`ローマ字名前`とのことでしたので変更し直しました。
`yukimorohosi`>`html-nri`>各々フォルダを作成してくということだと思いますが
下記参照のサイトを見ながら実施していたのですがイマイチできない状態です。


**【試してみたことと参考】**
`・空のディレクトリを下記参考に作りました
`https://qiita.com/tommy_aka_jps/items/b2ae85cbeab77e12a925
```

ここから下記参考に移動を試みたのですが、何が起きてるか不明です。
（試験的にhtmr-nriのファイルを移動してみたのですが変わってないみたいです。）
```
https://docs.github.com/ja/github/managing-files-in-a-repository/moving-a-file-to-a-new-location


そもそもターミナルからコマンドを活用しながら実施するが常なのでしょうか。
html-nriのディレクトリは作成できたと思うのですが各々を移動するのができてない状態のはずなので
土曜の際にでも構いませんので教えていただけないでしょうか。

2020-09-21 08:08 UTC, moroyou commented
> 追加でレビューしました。
> 
> 一部横展開（類似箇所の確認）が漏れている印象です。確認をお願いします。
> 
> また、個人的な感想ですが、複数の要因による問題が多いように思います。
> 問題を分析する時は細かく分けて分析をするようにしてください。
> 一つの要素に焦点をあて値を変えて問題がなければ他の要素を変えてみるなどしてみてください。



ありがとうございます。
ここでいう`複数の要因による問題`というのはHTML/CSSの記述とは別に
個人としての課題究明や対応施策の実施する能力という観点の理解で正しいでしょうか？？

その上で`問題を分析する時は細かく分けて分析をするようにしてください。`という認識で合っていますでしょうか。

上記理解で正しければ仰る通りであるのと、仮に違う場合でも
この観点は弱いなと思った（全体的に表面上で何事も解決しようとしてるなと感じた）ので意識します。

2020-09-23 22:55 UTC, n06Ar commented
一旦いただいたコメントについて、回答します。
> 【今回の話と質問】
yukimorohosi>html-nri>各々フォルダを作成してくということだと思いますが
下記参照のサイトを見ながら実施していたのですがイマイチできない状態です。

先ほど確認したところできていたので問題ないです。
この対応をいつ頃始めたか土曜日に教えてください。
私の見落としの可能性を感じているので確認したい次第です。
（該当のコミットをお教えいただけると幸いです）

>【試してみたことと参考】
・空のディレクトリを下記参考に作りました

確かにGitHub上で作業できるのですが、基本的にコーディングなどの作業はご自身のPC上で行う方が良いです。
GitHubで作業した場合は、変更をfetchして作業しているブランチにmergeする必要があるので（git pullのことです）

> そもそもターミナルからコマンドを活用しながら実施するが常なのでしょうか。
ディレクトリを作る話についてでしょうか？、Gitの操作を含めた操作のことでしょうか？
一応両者について回答しておくと、正直なmacOSでのFinderでもWindowsでのExplorer、SourceTreeでも使えるものを使ったら良いです。
ターミナルを使うのは、共通したコマンドがあることと、マウスを使った操作ではないので、キーボードで完結できることとやり方を文字だけで示せるメリットがあるからですね。

>ここでいう複数の要因による問題というのはHTML/CSSの記述とは別に
個人としての問題（課題）究明や対応施策の実施する能力という観点の理解で正しいでしょうか？？

間違えないでいただきたのですが、ないのではなくあまり強くない印象がある程度の認識です。
やっていて気が付いたと思いますが、HTML/CSSは簡単に関連の要素に影響を与え複雑な状況を作ることができます。
そのため、問題に対する原因の分析が必要になります。

2020-09-23 22:57 UTC, n06Ar commented on nri.html
> +                                <p><a href="#">NRIの歩みと持続的な成長</a></p>
こちら私の画面では修正を確認できないので、後ほど画面共有で確認させてください

2020-09-23 23:02 UTC, n06Ar commented on nri.html
> +            <div id="subinfo">
こちら修正が確認できませんでした。
#subinfoに、最大の横幅を決めて左右のマージンを自動にするとできます

2020-09-23 23:06 UTC, n06Ar commented on nri.html
> +        <header id="pagehead">
こちら修正を確認できませんでした。
横幅が1980pxで発生しています。
下記のような違いがあるのでご確認をお願いします
- 元のページ
![Screen Shot 2020-09-24 at 8 04 11](https://user-images.githubusercontent.com/56122838/94082755-99cc0900-fe3c-11ea-8485-1663e2e534b2.png)

- このリポジトリのもの
![Screen Shot 2020-09-24 at 8 03 56](https://user-images.githubusercontent.com/56122838/94082764-a0f31700-fe3c-11ea-8ea6-5b003522f785.png)

2020-09-23 23:08 UTC, n06Ar commented on nri.html
> +                        <li><a href="#">ナレッジ・インサイト</a></li>
こちらのコメントについては、HTMLの文書的な意味として見出しタグを使用して欲しい意図です。

2020-09-23 23:19 UTC, n06Ar requested changes
過去にコメントしたものに関連したものが修正されていなかったのでコメントしましたご確認をお願いします。

2020-09-23 23:19 UTC, n06Ar commented on nri.html
> +                <img class="topimg" src="image/top.page.jpg" "aria-hidden=" true" width="100%" height="100%">
`"aria-hidden=" true"`こちらですが、過去にコメントした通り`aria-hidden="true"`に修正をお願いします。

2020-09-23 23:19 UTC, n06Ar commented on nri.html
> +                    <h1 class="heading-type-main"><img src="image/nri-contentlogo.png" alt="nrimロゴ" "aria-hidden=" true"
`"aria-hidden=" true"` 👀

2020-09-23 23:19 UTC, n06Ar commented on nri.html
> +                    <li class="firstsns"><img src="image/facebook.logo.jpg" alt="facebokkのロゴ" width="30" height="30">
細かいのですが、`facebokkのロゴ`とタイポしています。

2020-09-24 08:45 UTC, moroyou commented on nri.html
> +                                <p><a href="#">NRIの歩みと持続的な成長</a></p>
承知いたしました。
土曜日にお願いいたします。念の為自身の画面では揃えてあるのでキャプチャだけん添付しておきます。
![image](https://user-images.githubusercontent.com/67782125/94122105-1555a680-fe8d-11ea-801a-46229e26beb9.png)

2020-09-24 08:45 UTC, moroyou commented on nri.html
> +                        <li><a href="#">ナレッジ・インサイト</a></li>
h4の見出しとして変更してみました。

2020-09-24 08:46 UTC, moroyou commented on nri.html
> +            <div id="subinfo">
こちら再度修正してみました。
ただ、多分理解できていない気がしているので土曜日にご質問させてください。

2020-09-24 08:51 UTC, moroyou commented on nri.html
> +        <header id="pagehead">
> 一旦いただいたコメントについて、回答します。
> 
> > 【今回の話と質問】
> > yukimorohosi>html-nri>各々フォルダを作成してくということだと思いますが
> > 下記参照のサイトを見ながら実施していたのですがイマイチできない状態です。
> 
> 先ほど確認したところできていたので問題ないです。
> この対応をいつ頃始めたか土曜日に教えてください。
> 私の見落としの可能性を感じているので確認したい次第です。
> （該当のコミットをお教えいただけると幸いです）
> 
> > 【試してみたことと参考】
> > ・空のディレクトリを下記参考に作りました
> 
> 確かにGitHub上で作業できるのですが、基本的にコーディングなどの作業はご自身のPC上で行う方が良いです。
> GitHubで作業した場合は、変更をfetchして作業しているブランチにmergeする必要があるので（git pullのことです）
> 
> > そもそもターミナルからコマンドを活用しながら実施するが常なのでしょうか。
> > ディレクトリを作る話についてでしょうか？、Gitの操作を含めた操作のことでしょうか？
> > 一応両者について回答しておくと、正直なmacOSでのFinderでもWindowsでのExplorer、SourceTreeでも使えるものを使ったら良いです。
> 
> ターミナルを使うのは、共通したコマンドがあることと、マウスを使った操作ではないので、キーボードで完結できることとやり方を文字だけで示せるメリットがあるからですね。
> 
> > ここでいう複数の要因による問題というのはHTML/CSSの記述とは別に
> > 個人としての問題（課題）究明や対応施策の実施する能力という観点の理解で正しいでしょうか？？
> 
> 間違えないでいただきたのですが、ないのではなくあまり強くない印象がある程度の認識です。
> やっていて気が付いたと思いますが、HTML/CSSは簡単に関連の要素に影響を与え複雑な状況を作ることができます。
> そのため、問題に対する原因の分析が必要になります。


ありがとうございます！
・Gitについては土曜日に再度共有とのことで承知致しました。
（ただ個人的にはやはりできてる気がしてないのでここも別途質問致します）

・原因の分析についてもコメントありがとうございます。
そもそも自分の場合は上記に加えて、根本的にまだ理解が浅いことが、影響範囲を考える上で視野を狭くしているとも気づきました。進捗はかなり遅い方だと思いますが、普段とは頭の動かし方が異る点や、こうしたFBいただける面は非常に個人的には勉強になるのでありがたいです。引き続きよろしくお願いいたします。

2020-09-27 08:42 UTC, moroyou commented
昨日の質問タイムでの口頭部分も含めて修正いたしました。

個人的にグローバルナビの部分が最後どうしてもうまくいっていない気がしているので
その点アドバイスいただけると幸いです。
`画面サイズを縮小すると文字の羅列だけどうしても変更してしまう`

それ以外はおそらく修正できているかと思いますが
ご確認よろしくお願いいたします。

2020-09-28 13:14 UTC, n06Ar requested changes
追加のコメントをしました。
ご確認をお願いいたします。

2020-09-28 13:14 UTC, n06Ar commented on html-nri/nri.html
> +            <div class="logo"><a href="#"><img src="image/nrilogo.png" alt="NRIロゴ" width="90" height="90"></a>
右側にマージンをつけて余白が欲しいです。

2020-09-28 13:14 UTC, n06Ar commented on html-nri/CSS/nri.css
> +    width: 95%;
width:100%で
ここは、max-widthを設定してください（1300pxあたり）

2020-09-28 13:14 UTC, n06Ar commented on html-nri/nri.html
> +                    <h4 class="subinfo-list-ul-first-title"><a href="#">ナレッジ・インサイト</a></h4>
h4では、企業情報の事業案内のコンテンツの小見出し扱いになるので、h2を使用する方が良いです。
類似箇所も同様です。

2020-09-28 13:14 UTC, n06Ar commented on html-nri/nri.html
> +                        <ul class="subinfo-list-ul-detail">
ここは2重のリストにする必要がないです。
また、`ul`の配下に`h4`は使用できません。
使用できる親子関係については[HTML5入れ子チートシート](https://yoshikawaweb.com/element/)を参照してください。

下記のようなHTML構造にすると良いです（クラスはあえて削除しているので、後で入力してください）
```html
<section class="subinfo-list">
  <h2><a href="#">ナレッジ・インサイト</a></h2>
  <ul>
    <li><a href="#">刊行物</a></li>
    <li><a href="#">書籍</a></li>
    <li><a href="#">コラム</a></li>
    <li><a href="#">セミナー資料</a></li>
    <li><a href="#">レポート</a></li>
    <li><a href="#">用語解説</a></li>
  </ul>
</section>
```

2020-10-03 14:46 UTC, n06Ar requested changes
今度こそ最後となると思われるコメントをしました。
こちらを直せば他は問題ないです。

2020-10-03 14:46 UTC, n06Ar commented on html-nri/CSS/nri.css
> +    width: 100%;
この横幅の設定ごと削除するか、`box-sizing:border-box;`をこのセレクタのスタイルに追加してください。
マージンとこの横幅の設定のおかげで、右にスクロールできるようようになっています。

2020-10-03 14:46 UTC, n06Ar commented on html-nri/nri.html
> +            <figure>
このfigureタグを削除するか、classを定義してブラウザが設定しているマージンを消してください。
またその後、`topimage`クラスのmargin-leftを削除してください。

この画像は装飾であり、セマンティクス的な意味を持たないためfigureタグを使用する必要がないためです。

2020-10-03 14:46 UTC, n06Ar commented on html-nri/CSS/nri.css
> +    margin-bottom: 30px;
`#smallglobalNavi`と同じ階層の下の要素の`main`タグとの余白を、`#smallglobalNavi`の子要素である`#smallglobalNavi ul li`で余白を作らせないでください。
他の人が修正する際に、どこを直せば良いかわからず、`#smallglobalNavi`にmarginを追加して複雑なCSSが出来上がる未来が想像できるためです。

2020-10-03 14:46 UTC, n06Ar commented on html-nri/CSS/nri.css
> +    float: left;
`float`を使っているため、ここは高さを持たないため、`ul`タグ`display:flex`を使いフレキシブルボックスで対応するか、floatの代わりに、`display:inline-block`を使い対応してください。

2020-10-04 08:44 UTC, moroyou commented
FB多くてすみません。こちらで修正できたかと思います。
ご確認よろしくお願いたします。

2020-10-04 08:51 UTC, n06Ar approved these changes
LGTMです！つまりOKです！
このプルリクエストをマージして、次の課題に進んでください。

2020-10-04 08:51 UTC, n06Ar commented on html-nri/CSS/nri.css
> +    margin-left: 200px;
margin-leftで指定されていますが、`position: absolute;`が指定されている場合ですとleftが使えるので、覚えておいてください。
[left - CSS](https://developer.mozilla.org/ja/docs/Web/CSS/left)

2020-10-04 09:02 UTC, merged